### PR TITLE
Add support for well-mixed, blended electrodes that contain more than one active material

### PR DESCRIPTION
**Pull request by ikorotkin**
Following the implementation idea from the [discussions](https://github.com/pybamm-team/BPX/discussions/22), I basically replaced `negative_electrode: Electrode` with a `Union`:
`negative_electrode: Union[Electrode, Dict[str, Electrode]]`, so that both single and blended electrodes will be supported.

I.e., for non-blended electrodes, nothing changes in the standard:
```
"Negative electrode": {
    "Particle radius [m]": 4.12e-06,
    "Thickness [m]": 5.62e-05,
    ...
}
```

And blended electrodes can be defined as
```
"Negative electrode": {
    "Primary": {
        "Particle radius [m]": 4.12e-06,
        "Thickness [m]": 5.62e-05,
        ...
    },
    "Secondary": {
        "Particle radius [m]": 4.12e-06,
        "Thickness [m]": 5.62e-05,
        ...
    },
    ....
}
```

Related to issue #23.

### CODE REVIEW

**Comment by ejfdickinson** [comment]
I don't get how this is supposed to work for those properties that describe the electrode composite, rather than the materials themselves. What happens if you set two different values for `"Thickness [m]"` between two blend components, for instance?

I would see the following as being strictly properties of the `electrode` that should not be stated more than once:

- "Thickness [m]"
- "Conductivity [S.m-1]"
- "Porosity"
- "Transport efficiency"

**Comment by tinosulzer** [comment]
This seems like a good solution. For naming, instead of `ElectrodeChemistry` and `ElectrodeOther`, can I suggest `Electrode` and `Particle`.

**Comment by ikorotkin** [comment]
That sounds like a good idea to me, thanks @tinosulzer.
Renamed the classes. Also, renamed the `Chemistry` field to `Particle`. Now JSON file can look like this:
```json
"Positive electrode": {
    "Thickness [m]": 75.6e-6,
    "Conductivity [S.m-1]": 0.18,
    "Porosity": 0.335,
    "Transport efficiency": 0.1939,
    "Particle": {
        "Primary": {
            "Particle radius [m]": 5.22e-6,
            "Diffusivity [m2.s-1]": 4.0e-15,
            "OCP [V]": {"x": [0, 0.1, 1], "y": [1.72, 1.2, 0.06]},
            "Surface area per unit volume [m-1]": 382184,
            "Reaction rate constant [mol.m-2.s-1]": 1e-10,
            "Maximum concentration [mol.m-3]": 63104.0,
            "Minimum stoichiometry": 0.1,
            "Maximum stoichiometry": 0.9,
        },
        "Secondary": {
            "Particle radius [m]": 10.0e-6,
            "Diffusivity [m2.s-1]": 4.0e-15,
            "OCP [V]": {"x": [0, 0.1, 1], "y": [1.72, 1.2, 0.06]},
            "Surface area per unit volume [m-1]": 382184,
            "Reaction rate constant [mol.m-2.s-1]": 1e-10,
            "Maximum concentration [mol.m-3]": 63104.0,
            "Minimum stoichiometry": 0.1,
            "Maximum stoichiometry": 0.9,
        },
        ...
    },
},
```
Note that the old structure (for single electrode chemistry) is still valid:
```json
"Negative electrode": {
    "Particle radius [m]": 5.86e-6,
    "Thickness [m]": 85.2e-6,
    "Diffusivity [m2.s-1]": 3.3e-14,
    "OCP [V]": {"x": [0, 0.1, 1], "y": [1.72, 1.2, 0.06]},
    "Conductivity [S.m-1]": 215.0,
    "Surface area per unit volume [m-1]": 383959,
    "Porosity": 0.25,
    "Transport efficiency": 0.125,
    "Reaction rate constant [mol.m-2.s-1]": 1e-10,
    "Maximum concentration [mol.m-3]": 33133,
    "Minimum stoichiometry": 0.01,
    "Maximum stoichiometry": 0.99,
},
```
This PR won't break old BPX files.

And I feel like the `Particle` class will be useful for SPM and SPMe models (issue #29).

These are just suggestions, feel free to correct me.

**Comment by ejfdickinson** [comment]
Nice work @ikorotkin !

I think that this solution looks good, and I'm happy with the revised nomenclature. Shall we think about widening the set of test cases so that pass/fail can be checked against correct or pathological JSON instances expressing blended electrodes?

I'd suggest that we consider merging this PR and then branching the discussion point raised by me and @rtimms (on replacing `Surface area per unit volume [m-1]` with a mass- or volume-fraction-based definition, https://github.com/pybamm-team/BPX/pull/33#issuecomment-1598562147) into a new issue with a new PR.

**Comment by ejfdickinson** [comment]
Comments related to the replacement of `Surface area per unit volume [m-1]` are now replicated (branched) in #41 .

No further issues on the content of this PR, though the new functionality needs some suitable tests.

**Review by rtimms — APPROVED** [review]
thanks @ikorotkin looks good! can you add an entry to the changelog.

**Pull request merged**
